Repository cloudfoundry/bpm-release, pull requests merged in 2018-06, with the labels that each got.

#63 remove restriction on allowed capabilities
  CHANGELOG.md
  docs/config.md
  src/bpm/config/job_config.go
  src/bpm/config/job_config_test.go
Labels: unscheduled

#62 Communicate to R&D that bpm necessitates blackbox
  docs/transitioning.md
Labels: unscheduled

#65 Sort mounts by length of destination in container
  CHANGELOG.md
  src/bpm/runc/adapter/adapter.go
  src/bpm/runc/adapter/adapter_test.go
Labels: scheduled

#59 Add support for unrestricted volumes
  CHANGELOG.md
  docs/config.md
  src/bpm/config/fixtures/example.yml
  src/bpm/config/job_config.go
  src/bpm/config/job_config_test.go
  src/bpm/runc/adapter/adapter.go
  src/bpm/runc/adapter/adapter_test.go
Labels: enhancement, unscheduled
